#!/usr/bin/env bash

kms() {
  exit 111
}

exitfn() {
  trap SIGINT
  kms
}

trap "exitfn" INT

[ -z "$1" ] && echo "need to specify environment" && kms

./configure_inventory $1 || kms

KEY_NAME=$(./terraform_output $1 key_name)

export ANSIBLE_SSH_PIPELINING=True

ansible-playbook ansible/configure_server.yml -i terraform/environment/$1/inventory --key-file=~/$KEY_NAME.pem || kms