---
- hosts: appservers
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: copy release binary
      copy: src={{playbook_dir}}/../rust/target/release/vromio dest=/opt/vromio/